import { expect, test, type Page } from "@playwright/test";
import { readFile } from "node:fs/promises";

// The UI is bilingual; these flows exercise the English locale. The Chinese UI
// is the same dictionary translated, so it needs no separate coverage. Report
// bodies ("核心结论") are generated by the mock backend and stay Chinese
// regardless of the interface language.

const ASK_PLACEHOLDER = /Ask a research question/;
const isolatedBackendPort = process.env.PLAYWRIGHT_BACKEND_PORT;

async function routeToIsolatedBackend(page: Page) {
  if (!isolatedBackendPort || isolatedBackendPort === "8000") return;
  await page.route("http://localhost:8000/**", (route) => {
    const url = route.request().url().replace("http://localhost:8000", `http://127.0.0.1:${isolatedBackendPort}`);
    return route.continue({ url });
  });
}

async function openWorkbench(page: Page) {
  await routeToIsolatedBackend(page);
  // Pin the locale to English before any app script runs (survives reloads).
  await page.addInitScript(() => {
    try {
      window.localStorage.setItem("pz-deep-research-locale", "en");
    } catch {
      // ignore storage failures
    }
  });
  await page.goto("/workbench");
  await page.evaluate(() => window.localStorage.clear());
  await page.reload();
  await expect(page.getByPlaceholder(ASK_PLACEHOLDER)).toBeEnabled();
}

async function startResearch(page: Page, query: string, mode = "Quick") {
  await page.getByRole("tab", { name: mode, exact: true }).click();
  await page.getByPlaceholder(ASK_PLACEHOLDER).fill(query);
  await page.getByRole("button", { name: "Start research", exact: true }).click();
}

const jobIdChip = (page: Page) => page.locator(".run-meta .mono").first();

test.beforeEach(async ({ page }) => {
  await openWorkbench(page);
});

test("can cancel a running research task and keep the captured progress", async ({ page }) => {
  await startResearch(page, "Validate cancelling a research task");

  await expect(jobIdChip(page)).toBeVisible();
  const cancelButton = page.getByRole("button", { name: "Cancel research", exact: true });
  await expect(cancelButton).toBeVisible();
  await cancelButton.click();

  await expect(page.getByText("Research cancelled", { exact: true })).toBeVisible();
  await expect(page.locator(".job-status")).toHaveText("Cancelled");
});

test("restores a running task after refresh and recovers the finished report", async ({ page }) => {
  const query = "Validate task recovery after refresh";
  await startResearch(page, query);

  await expect(jobIdChip(page)).toBeVisible();
  const persistedJobId = (await jobIdChip(page).textContent())?.trim() || "";
  expect(persistedJobId).not.toBe("");

  await page.reload();

  await expect(page.getByRole("heading", { name: query })).toBeVisible();
  await expect(jobIdChip(page)).toContainText(persistedJobId);
  await expect(page.locator(".job-status")).toHaveText("Completed", { timeout: 30_000 });
  await expect(page.locator(".report-body")).toContainText("核心结论");

  await page.reload();

  await expect(jobIdChip(page)).toContainText(persistedJobId);
  await expect(page.locator(".report-body")).toContainText("核心结论");
});

test("a completed task shows up in the guest's sidebar history", async ({ page }) => {
  const query = `Validate research history ${Date.now()}`;
  await startResearch(page, query);
  await expect(page.locator(".job-status")).toHaveText("Completed", { timeout: 30_000 });

  await page.getByRole("button", { name: "New research", exact: true }).click();
  await expect(page.getByPlaceholder(ASK_PLACEHOLDER)).toBeVisible();

  const historyItem = page.locator(".history-list button", { hasText: query });
  await expect(historyItem).toBeVisible();
  await historyItem.click();

  await expect(page.getByRole("heading", { name: query })).toBeVisible();
  await expect(page.locator(".job-status")).toHaveText("Completed");
  await expect(page.locator(".report-body")).toContainText("核心结论");
});

test("can re-run a report and create an independent task", async ({ page }) => {
  const query = `Validate re-run ${Date.now()}`;
  await startResearch(page, query);
  await expect(page.locator(".job-status")).toHaveText("Completed", { timeout: 30_000 });
  const originalJobId = (await jobIdChip(page).textContent())?.trim() || "";

  await page.getByRole("button", { name: "Re-run", exact: true }).click();

  await expect(page.getByRole("heading", { name: query })).toBeVisible();
  await expect(jobIdChip(page)).not.toHaveText(originalJobId);
  await expect(page.locator(".job-status")).toHaveText("Completed", { timeout: 30_000 });
  await expect(page.locator(".report-body")).toContainText("核心结论");
});

test("can export the current report as a Markdown file", async ({ page }) => {
  const query = "Validate Markdown export filename";
  await startResearch(page, query);
  await expect(page.locator(".job-status")).toHaveText("Completed", { timeout: 30_000 });

  const exportButton = page.getByRole("button", { name: "Export Markdown", exact: true });
  await expect(exportButton).toBeEnabled();

  const downloadPromise = page.waitForEvent("download");
  await exportButton.click();
  const download = await downloadPromise;

  expect(download.suggestedFilename()).toBe("Validate-Markdown-export-filename.md");
  const downloadPath = await download.path();
  expect(downloadPath).not.toBeNull();
  const content = await readFile(downloadPath!, "utf8");
  expect(content).toContain("## 核心结论");
  expect(content).toContain("PZ Deep Research");
  expect(content.endsWith("\n")).toBe(true);
});

test("can export the current report as a PDF file", async ({ page }) => {
  const query = "Validate PDF export filename";
  await startResearch(page, query);
  await expect(page.locator(".job-status")).toHaveText("Completed", { timeout: 30_000 });

  const exportButton = page.getByRole("button", { name: "Export PDF", exact: true });
  await expect(exportButton).toBeEnabled();

  const downloadPromise = page.waitForEvent("download");
  await exportButton.click();
  const download = await downloadPromise;

  expect(download.suggestedFilename()).toMatch(/\.pdf$/);
  const downloadPath = await download.path();
  expect(downloadPath).not.toBeNull();
  const content = await readFile(downloadPath!);
  expect(content.subarray(0, 5).toString("ascii")).toBe("%PDF-");
  expect(content.subarray(-1024).toString("latin1")).toContain("%%EOF");
  expect(content.length).toBeGreaterThan(8_000);
});

test("a failed task shows a productized error and recovers via a single retry button", async ({ page }) => {
  const failedJob = {
    id: "failed-job",
    rerun_of_job_id: null,
    query: "验证产品化错误重试",
    mode: "quick",
    provider: "mock",
    model: null,
    status: "failed",
    draft_report: "",
    final_report: null,
    error: "网络连接不稳定，请检查网络后重试。",
    error_code: "network_error",
    error_retryable: true,
    error_stage: "search",
    created_at: "2026-06-10T12:00:00Z",
    updated_at: "2026-06-10T12:01:00Z",
  };
  const retryJob = {
    ...failedJob,
    id: "retry-job",
    rerun_of_job_id: failedJob.id,
    status: "queued",
    error: null,
    error_code: null,
    error_retryable: false,
    error_stage: null,
    updated_at: "2026-06-10T12:02:00Z",
  };

  await page.route("**/api/research-jobs/failed-job", async (route) => {
    await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(failedJob) });
  });
  await page.route("**/api/research-jobs/failed-job/retry", async (route) => {
    await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(retryJob) });
  });
  await page.route("**/api/research-jobs/failed-job/events", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify([
        {
          id: "failed-event",
          job_id: failedJob.id,
          type: "failed",
          message: failedJob.error,
          payload: {
            error_code: failedJob.error_code,
            retryable: true,
            stage: failedJob.error_stage,
          },
          created_at: failedJob.updated_at,
        },
      ]),
    });
  });
  await page.route("**/api/research-jobs/retry-job/stream**", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "text/event-stream",
      body: `data: ${JSON.stringify({
        id: "retry-status",
        job_id: retryJob.id,
        type: "status",
        message: "Research restarted",
        payload: {},
        created_at: retryJob.updated_at,
      })}\n\n`,
    });
  });

  await page.evaluate(() => {
    window.localStorage.setItem("pz-deep-research-active-job", "failed-job");
  });
  await page.reload();

  await expect(page.locator(".fail-card")).toContainText(failedJob.error);
  await expect(page.getByText(/invalid api key|Traceback|provider/i)).toHaveCount(0);

  const retryButton = page.getByRole("button", { name: "Retry research", exact: true });
  await expect(retryButton).toBeVisible();
  await expect(page.getByRole("button", { name: "Re-run", exact: true })).toHaveCount(0);

  await retryButton.click();

  await expect(jobIdChip(page)).toContainText(retryJob.id);
  await expect(page.getByRole("heading", { name: retryJob.query })).toBeVisible();
});
